server:
  port: 9000
  http2:
    enabled: true
spring:
  application:
    name: spring-webflux-guide
  webflux:
    base-path: /api
  cache:
    type: redis
  data:
    redis:
      password:
      host: localhost
      username:
      connect-timeout: 30s
      port: 6379

logging:
  level:
    io:
      reflectoring: DEBUG
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG