server:
  port: 9000
  http2:
    enabled: true
spring:
  application:
    name: spring-webflux-guide
  web-flux:
    base-path: /api/v1/
  cache:
    type: redis
  data:
    redis:
      password:
      host: localhost
      username:
      connect-timeout: 30s
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    queue:
      name: value-cache-q

logging:
  level:
    io:
      reflector: DEBUG
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

schedule:
  cron: "*/10 * * * * ?"